// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DialogComponent: typeof import('./components/DialogComponent.vue')['default']
    TicketsTableComponent: typeof import('./components/TicketsTableComponent.vue')['default']
  }
}

export { }
